#!/bin/bash

printf "# %s\n" "${2:-CPE Status}"
printf "\n"
printf "Date: %s\n" "`date`"
printf "\n"
printf "| Port | Maintainer | Status | Comment |\n"
printf "|--|--|--|--|\n"

while read line
do
  IFS=$'\t' read -r PORT MAINTAINER STATUS COMMENT <<< "$line"

  printf "| [%s](https://freshports.org/%s) | %s | `%s` | %s |\n" \
    $PORT $PORT $MAINTAINER $STATUS "$COMMENT"
done < "${1:-/dev/stdin}"

