#!/usr/bin/env php
<?php

$title = "CPE Status";

if(isset($argv[1]))
   $title = $argv[1];

$statusmap = array(
   'valid'   => 'brightgreen',
   'invalid' => 'red',
   'missing' => 'orange',
   'unknown' => 'grey'
);

printf("# %s\n", $title);
printf("\n");
printf("Date: %s\n", date(DATE_RFC850));
printf("\n");
printf("| Port | Maintainer | Status | Comment |\n");
printf("|--|--|--|--|\n");

for($i=1; ($line = fgets(STDIN)) !== false; $i++)
{
   if(strlen(trim($line)) < 1)
      continue;

   $parts = explode("\t", $line);

   if(count($parts) != 4){
      fwrite(STDERR, "Invalid line ".$i."\n");
      continue;
   }

   list($port, $maintainer, $status, $comment) = array_map('trim', $parts);
   $status = strtolower($status);
   $color = 'black';

   if(isset($statusmap[$status]))
      $color = $statusmap[$status];

   printf("| [%s](https://freshports.org/%s) | %s | ![%s](https://img.shields.io/badge/%s-%s) | %s |\n",
      $port, $port, $maintainer, $status, $status, $color, $comment);
}

